// ============================================================
// XFLIX — Mock Data
// Fictional videos for home page (no database)
// ============================================================

import type { Video } from "@/types";

export const MOCK_VIDEOS: Video[] = [
  {
    id: "1",
    title: "Dominando Next.js 15 do Zero ao Avançado",
    description:
      "Aprenda Next.js 15 com App Router, Server Components e muito mais neste curso completo.",
    slug: "dominando-nextjs-15",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=450&fit=crop",
      alt: "Next.js 15 Course",
    },
    author: { id: "a1", name: "Carlos Mendes", verified: true },
    category: "Programação",
    tags: ["nextjs", "react", "typescript"],
    duration: 14400,
    views: 48200,
    likes: 3100,
    rating: 4.9,
    price: 49.99,
    pricing: "paid",
    status: "published",
    isFeatured: true,
    isNew: false,
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "2",
    title: "Design Systems com Figma e Tailwind CSS",
    description:
      "Crie sistemas de design profissionais e implemente-os com Tailwind CSS.",
    slug: "design-systems-figma-tailwind",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&h=450&fit=crop",
      alt: "Design Systems Course",
    },
    author: { id: "a2", name: "Ana Rodrigues", verified: true },
    category: "Design",
    tags: ["figma", "tailwind", "ui"],
    duration: 10800,
    views: 32100,
    likes: 2400,
    rating: 4.8,
    price: 39.99,
    pricing: "paid",
    status: "published",
    isFeatured: false,
    isNew: true,
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "3",
    title: "Marketing Digital para Criadores de Conteúdo",
    description:
      "Estratégias comprovadas para crescer a sua audiência e monetizar o seu conteúdo.",
    slug: "marketing-digital-criadores",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop",
      alt: "Digital Marketing",
    },
    author: { id: "a3", name: "Pedro Costa", verified: false },
    category: "Marketing",
    tags: ["marketing", "redes sociais", "crescimento"],
    duration: 7200,
    views: 21500,
    likes: 1800,
    rating: 4.6,
    price: 0,
    pricing: "free",
    status: "published",
    isFeatured: false,
    isNew: false,
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: "2024-10-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Finanças Pessoais: Invista com Inteligência",
    description:
      "Aprenda a investir, poupar e construir riqueza com estratégias simples e eficazes.",
    slug: "financas-pessoais-investir",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop",
      alt: "Personal Finance",
    },
    author: { id: "a4", name: "Sofia Alves", verified: true },
    category: "Finanças",
    tags: ["investimento", "finanças", "poupança"],
    duration: 9000,
    views: 55000,
    likes: 4200,
    rating: 4.9,
    price: 59.99,
    pricing: "paid",
    status: "published",
    isFeatured: true,
    isNew: false,
    createdAt: "2024-09-01T10:00:00Z",
    updatedAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "5",
    title: "TypeScript Avançado: Tipos, Generics e Patterns",
    description:
      "Domine TypeScript avançado com tipos condicionais, generics e design patterns.",
    slug: "typescript-avancado",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=450&fit=crop",
      alt: "TypeScript Advanced",
    },
    author: { id: "a1", name: "Carlos Mendes", verified: true },
    category: "Programação",
    tags: ["typescript", "javascript", "patterns"],
    duration: 12600,
    views: 38900,
    likes: 2900,
    rating: 4.8,
    price: 44.99,
    pricing: "paid",
    status: "published",
    isFeatured: false,
    isNew: true,
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "6",
    title: "Empreendedorismo Digital: Lance o Seu Negócio",
    description:
      "Do zero ao primeiro cliente: como criar e escalar um negócio digital com sucesso.",
    slug: "empreendedorismo-digital",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800&h=450&fit=crop",
      alt: "Digital Entrepreneurship",
    },
    author: { id: "a5", name: "Miguel Santos", verified: true },
    category: "Negócios",
    tags: ["negócio", "empreendedorismo", "digital"],
    duration: 11400,
    views: 29700,
    likes: 2100,
    rating: 4.7,
    price: 0,
    pricing: "free",
    status: "published",
    isFeatured: false,
    isNew: false,
    createdAt: "2024-08-20T10:00:00Z",
    updatedAt: "2024-08-20T10:00:00Z",
  },
  {
    id: "7",
    title: "UI/UX Design: Princípios e Práticas Modernas",
    description:
      "Crie interfaces intuitivas e belas com princípios sólidos de UI/UX design.",
    slug: "ui-ux-design-principios",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop",
      alt: "UI UX Design",
    },
    author: { id: "a2", name: "Ana Rodrigues", verified: true },
    category: "Design",
    tags: ["ui", "ux", "design"],
    duration: 8400,
    views: 41200,
    likes: 3400,
    rating: 4.9,
    price: 34.99,
    pricing: "paid",
    status: "published",
    isFeatured: false,
    isNew: false,
    createdAt: "2024-07-15T10:00:00Z",
    updatedAt: "2024-07-15T10:00:00Z",
  },
  {
    id: "8",
    title: "React Query & State Management Masterclass",
    description:
      "Gerencie estado de servidor com React Query e otimize performance das suas apps.",
    slug: "react-query-masterclass",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=450&fit=crop",
      alt: "React Query Masterclass",
    },
    author: { id: "a6", name: "Rui Ferreira", verified: true },
    category: "Programação",
    tags: ["react", "react-query", "estado"],
    duration: 9600,
    views: 27300,
    likes: 2200,
    rating: 4.7,
    price: 29.99,
    pricing: "paid",
    status: "published",
    isFeatured: false,
    isNew: true,
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-01T10:00:00Z",
  },
];

export const MOCK_FEATURED_VIDEO = MOCK_VIDEOS[0];
export const MOCK_TRENDING = MOCK_VIDEOS.slice(0, 6);
export const MOCK_NEW_RELEASES = MOCK_VIDEOS.filter((v) => v.isNew);
export const MOCK_FREE_VIDEOS = MOCK_VIDEOS.filter(
  (v) => v.pricing === "free"
);
